# This file was generated by GoReleaser. DO NOT EDIT.
class Fastly < Formula
  desc "Fastly CLI"
  homepage "https://github.com/fastly/cli"
  version "0.13.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fastly/cli/releases/download/v0.13.0/fastly_v0.13.0_darwin-amd64.tar.gz"
    sha256 "e819bf9a840ca15c7767c80eb1661a7aceb78e22b43d0166f5d07f1f7af9e9a6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/fastly/cli/releases/download/v0.13.0/fastly_v0.13.0_linux-amd64.tar.gz"
      sha256 "854abf94ba1d1a1c5e852eafd220fbe3e14bdbe1b7c53dd565c239aee029a006"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fastly/cli/releases/download/v0.13.0/fastly_v0.13.0_linux-arm64.tar.gz"
        sha256 "3daf0be252f3a9e7471d600b5889093e15d5a3dbb427e17101d25d88403ffe0b"
      else
      end
    end
  end
  
  head do
    url "https://github.com/fastly/cli.git"
    depends_on "go"
  end

  def install
    system "make" if build.head?
    bin.install "fastly"
    (bash_completion/"fastly.sh").write `#{bin}/fastly --completion-script-bash`
    (zsh_completion/"_fastly").write `#{bin}/fastly --completion-script-zsh`
  end

  test do
    help_text = shell_output("#{bin}/fastly --help")
    assert_includes help_text, "Usage:"
  end
end
