# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ngwafctl < Formula
  desc "A CLI for interacting with the Next-Gen WAF platform"
  homepage "https://docs.fastly.com/en/ngwaf/using-the-ngwaf-core-command-line-utility"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://dl.signalsciences.net/ngwafctl/0.1.0/ngwafctl_0.1.0_darwin_arm64.tar.gz"
      sha256 "cd61f0c6cba67608076b599326bd9b277c076c5aa772f9e9d4ad99b1afd870b8"

      def install
        bin.install "ngwafctl"
        (bash_completion/"ngwafctl.sh").write `#{bin}/ngwafctl completion bash`
        (zsh_completion/"_ngwafctl").write `#{bin}/ngwafctl completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://dl.signalsciences.net/ngwafctl/0.1.0/ngwafctl_0.1.0_darwin_amd64.tar.gz"
      sha256 "6886146afc04d348ce7e81b6f999144aad144a7b874851d15fd5da44ada0e9f5"

      def install
        bin.install "ngwafctl"
        (bash_completion/"ngwafctl.sh").write `#{bin}/ngwafctl completion bash`
        (zsh_completion/"_ngwafctl").write `#{bin}/ngwafctl completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://dl.signalsciences.net/ngwafctl/0.1.0/ngwafctl_0.1.0_linux_amd64.tar.gz"
      sha256 "4e46d2ba7660e1d4390af887f000e52714bc8e13c0da80c2db36b8bc75e1b0f8"

      def install
        bin.install "ngwafctl"
        (bash_completion/"ngwafctl.sh").write `#{bin}/ngwafctl completion bash`
        (zsh_completion/"_ngwafctl").write `#{bin}/ngwafctl completion zsh`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.signalsciences.net/ngwafctl/0.1.0/ngwafctl_0.1.0_linux_arm64.tar.gz"
      sha256 "2a9ba2a08cd91423d84c767f9d0a989bda5c146d90a0aace22c304dfed42295f"

      def install
        bin.install "ngwafctl"
        (bash_completion/"ngwafctl.sh").write `#{bin}/ngwafctl completion bash`
        (zsh_completion/"_ngwafctl").write `#{bin}/ngwafctl completion zsh`
      end
    end
  end

  head do
    url "https://docs.fastly.com/en/ngwaf/using-the-ngwaf-core-command-line-utility"
    depends_on "go"
  end

  test do
    help_text = shell_output("#{bin}/ngwafctl --help")
    assert_includes help_text, "Usage:"
  end
end
